# Generated by Django 2.2.15 on 2021-02-02 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='useres who are online in chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
